### ISSUE TITLE
Check spelling should ignore language keywords based on file type

### ISSUE THREAD

**Issue by MaT1g3R** [check-spelling/check-spelling#2]

**Comment by MaT1g3R** [comment]
Maybe we could have a directory for allowed words, then each of the file could look like this:

```
ft: *.py
words:
repr
addi
...........
```

**Comment by jsoref** [comment]
#### Workaround
To define multiple language sets, one should be able to do:

`.github/workflows/spelling.yml`:
```yml
name: Spell checking
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '5 * * * *'

jobs:
  spell-check:
    name: Spell checker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, java]
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 2
    - uses: check-spelling/check-spelling@master
      env:
        bucket: .github/actions/spelling
        project: ${{ matrix.language }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

* `.github/actions/spelling/common/`:
  * `advice.txt`:
    You can include advice explaining how to update things and when to put items into `common/` instead of into the specific directories.
  * `dictionary.txt`:
    *Your global dictionary*
  * `excludes.txt`
    *Your global excludes*
  * `patterns.txt`:
    *Your global patterns*
  * ⚠️ You probably do not want to include `whitelist` in `common/`.
* `.github/actions/spelling/python/`:
  * `advice.txt`:
    *symlink* to `../common/advice.txt`
  * `dictionary/`:
    * `dictionary.txt`:
      *symlink* to `../../common/dictionary.txt`
    * `python.txt`:
      *Python dictionary*
   * `excludes/`:
     * `excludes.txt`:
       *symlink* to `../../common/excludes.txt`
     * `python.txt`:
       *Rules to exclude non python files*
   * `whitelist/`:
      * `whitelist.txt`:
        *Python whitelist*
* `.github/actions/spelling/java/`:
  * `advice.txt`:
    *symlink* to `../common/advice.txt`
  * `dictionary/`:
    * `dictionary.txt`:
      *symlink* to `../../common/dictionary.txt`
    * `java.txt`:
      *Python dictionary*
   * `excludes/`:
     * `excludes.txt`:
       *symlink* to `../../common/excludes.txt`
     * `java.txt`:
       *Rules to exclude non java files*
   * `whitelist/`:
      * `whitelist.txt`:
        *Java whitelist*

The downside to this is that you will get distinct reports (i.e. potentially multiple comments) for spelling errors from different kinds of files.
On the bright side, I think, in many cases a developer is only writing changes in one language at a time.
-- I'd love to get some implementation experience here (i.e. if you're willing, let's try it).

It is possible for an action to pass data off to another stage, so it might be possible for me to add support for coalescing reports. 

If one wanted to be truly adventurous, the workflow file allows [scoping jobs to changed files](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns-1).


### Thoughts
#### Organization common config
GitHub itself has the concept of a magical per organization [.github](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) repository.
There's a [request to be able to use that for actions](https://github.community/t5/GitHub-Actions/Plans-to-support-global-workflows-in-github-repository/td-p/50718).
-- Afaiu, that isn't actually supported yet.

#### Per organization shared rules
Because of the way configurations work for this action, you could just add an extra `uses: actions/checkout@v2.0.0` to retrieve common elements into another directory and rely on symlink(s) to pull in those items.

#### Support for `includes`
I'm aware that I have `excludes` but not `includes`. I've been trying to figure out the right way to approach mixing them which is why I've so far not addressed it.

I suspect what I'll do is a simple `exclude excludes first` followed by `drop anything not included by includes`. That's fairly easy to reason through. If people need something more complicated, they could include some negative lookaheads in their excludes, or not put some things in their excludes and then rely on more complicated includes rules.

Offhand, I think this is probably the most important item to help make the workaround I describe at the top work. And it's pretty easy for me to write, so, I'll probably look into it this week.

#### Complicated config files
I'd like to avoid having to build/maintain a dictionary for each file I open. I know that I could cache it, but I really don't want to have to try to invent my own caching algorithm.

I also want to make it easy for people to add to the word list files w/o having to worry about things like indentation.

I've seen problems w/ other consumers involving line endings:
* one consumer had a user whose editor flipped the line endings on the whitelist which in an older version resulted in the whitelist being effectively discarded
* another project had `.gitconfig` which effectively did that globally

I've since added support for all line endings so that specific problem isn't a thing.

I really don't want to have to worry about **tabs** vs. **spaces** or various indentation rules.

I'd rather avoid implementing my own linter for my config file.

I have added some basic linting -- one to report when `patterns` (regular expressions) are broken -- because that's pretty easy to mess up regular expressions and the results can be very confusing.
