### ISSUE TITLE
Check submodules

### ISSUE THREAD

**Issue by Luko6** [check-spelling/check-spelling#32]
Is there an option, or could one be added to checkout submodules too when using the action?

**Comment by jsoref** [comment]
Oh, indeed, I don't have that, and because of the way it works, it won't do the right thing w/o some work.

You could cheat by having your workflow do something like this:

```yaml
steps:
 - name: checkout
    uses: actions/checkout@...
    with:
      submodules...
 - name: stub repo layout
   shell: bash
   run: |
     rm -rf .git
     git init .
     git add .
     git commit -m 'stub commit -- includes submodules'
 - name: check spelling
   uses: check-spelling/check-spelling@...
...
```

Do you have a sample repository I could look at? And is there a reason you'd want to run it in just the one repository as opposed to having it run in each of the submodules separately? -- My assumption (and I could be very wrong) is that github won't handle annotations for files from submodules particularly well.

**Comment by Luko6** [comment]
I tried this solution but I'm getting an error in the workflow

[Pull Request](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/157) using this [workflow](https://github.com/Lombiq/GitHub-Actions/blob/issue/OSOE-158/.github/workflows/check-spelling.yml) with your suggestion that utilizes this [action](https://github.com/Lombiq/GitHub-Actions/blob/issue/OSOE-158/.github/actions/check-spelling/action.yml)

We use superprojects with submodules, so it would be simply easier to set the action up this way once instead of multiple times in each submodule.

**Comment by jsoref** [comment]
The problem you tripped on is that the directory for the check-spelling configuration in the `spell-check-this` repository needs to be `.github/actions/spelling` -- the code itself in the version you're using is pretty buggy. If you _really_ need to be able to control the name of the directory inside the spell-check-this repository, I could add support for that, probably using the GitHub notation of `check-spelling/spell-check-this/.github/actions/check-spelling@example`, but I'd rather not if I don't need to

I've added some code to try to improve the error reporting (as well as fixed the inconsistencies in the logic).

With that, the hack described above seems to work:
https://github.com/jsoref/Open-Source-Orchard-Core-Extensions/actions/runs/3258368221

---

Handling submodules requires me to look into them a bit (I know they exist, but I don't really use them, and my general default is to actively suppress cloning them).

My general assumption is that I'll want to add a `submodules` option to checkout-merge and have it properly handle conflicts in submodules (which may require some amount of work, but will definitely require me to set up some repositories and test things).

After i've added a `submodules` option there, I'll want to add the same option to check-spelling. I think more or less this would mean occasionally passing `--recurse-submodules` to `git 'ls-files'` in `run_spell_check`.

Of course, actions/checkout supports both `true` and `recursive` and they do different things. I'm not really certain what `git ls-files` would do under any of these circumstances, so it'll definitely require some experimentation.

I guess I'd need to decide if I want `only_check_changed_files` to cooperate with `submodules`. In _theory_ it's possible in that I could get the old and new shas for each submodule and get the changed files for them.

I think what I'll probably do at the same time is add support for a `files_list` to contain the list of files to check which would allow someone to run `git ls-files -z --recurse-submodules > $files_list` and then use `with: files_list: ...` -- that would let people work around various assumptions that I may be making.

**Comment by jsoref** [comment]
The next version should support checking out submodules as well as checking submodules that are checked out by a calling workflow...

users will just need to add:

```yaml
- uses: check-spelling/check-spelling@v0.0.25 # this doesn't exist yet, but it should be available in `prerelease` by next week.
  with:
    # ...
    submodules: recursive # or "true"
```
