### ISSUE TITLE
Getting "cp: cannot create regular file '.git/': Not a directory" Error

### ISSUE THREAD

**Issue by praneesha** [check-spelling/check-spelling#7]
@jsoref - I have configured the spell-checker as follows:

```
on: [pull_request]
name: Check spelling
jobs:
  spellChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Check spelling
        uses: check-spelling/check-spelling@0.0.16-alpha
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 2
      - uses: ./
        with:
          bucket: .github/actions
          project: spelling
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
I am getting the following error.

`cp: cannot create regular file '.git/': Not a directory`

How can I get this resolved?

**Comment by jsoref** [comment]
Hmm, this doesn't quite look right. I think it should be closer to this:

```
on: [pull_request]
name: Check spelling
jobs:
  spellChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 2
      - name: Check spelling
        uses: check-spelling/check-spelling@0.0.16-alpha
        with:
          bucket: .github/actions
          project: spelling
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But you should be able to add `DEBUG: 1` to `env:` and then we should be able to get a better sense of what's going wrong (the line that I'd expect to fail is `cp $spellchecker/reporter.json .git/`)
