### ISSUE TITLE
Document how to exclude code snippets in markdown files

### ISSUE THREAD

**Issue by LukeStorry** [check-spelling/check-spelling#9]
I'm trying to add in exclusion for backticked code snippets so the contents don't get spell checked.

I've tried both `\x60{1,3}[\s\S]+?\x60{1,3}` and `\`[\n.]+?\`` and variations thereof, but can't seem to get the action to ignore the snippets.

For example:

---

# Section 4 - Encryption

Here is a sample encrypton function:

```python
def encrypt(message: str):
    # Do the encryption...
    return encrypted_message
```

The `encrypt` function takes one parameter...

**Comment by jsoref** [comment]
Unfortunately, there's currently no provision to handle multi-line things. I'm still thinking about how to do it :-(.

My concern is that people don't necessarily ignore binary files, which means there's a risk of the tool having to pull the entire file into memory.

I think to address this, I'll probably have to switch to a mode where I build my own state machine :-(.

**Comment by LukeStorry** [comment]
Ah, ok that makes sense!

Thanks for your speedy response too.

I can workaround by just adding all problematic words to `expect.txt`, but multi-line excludes would be handy!

**Comment by jsoref** [comment]
Yeah... agreed.

You can cheat by adding a regexp for `^*ignore-line.*$` and then adding `# ignore-line` to the line or similar.

So far, I've cheated by manually checking such files and then excluding the files. But that isn't great.

**Comment by LukeStorry** [comment]
Thanks, I'll use that in some places.

This seems to work for single-line backtick escaping: `\x60.+?\x60`

In some of the [examples ](https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples%3A-patterns) you put a `/` at the start of the regex, what difference does that make?

**Comment by jsoref** [comment]
If you mean things like:
```
/docs\.google\.com/[a-z]+/d/(?:e/|)[0-9a-zA-Z_-]+/
```
It assumes that a url is of the form:
* https://docs.google.com/hello/d/hello/

It would not catch:
* docs.google.com/hello/d/hello/

It's as opposed to:
```perl
\bdocs\.google\.com/[a-z]+/d/(?:e/|)[0-9a-zA-Z_-]+/
```
To avoid tripping over:
* mucdocs.google.com/hello/d/hello/

**Comment by LukeStorry** [comment]
Ah yes ok, was wondering why that didn't need escaping, or if it was signifying the beginning of the regex.
Cheers!

**Comment by jsoref** [comment]
I've added some extra comments to the entries in the wiki. Let me know if they're helpful.

I suppose I could actually include some examples of how they break (as I did above)....

**Comment by pudgereyem** [comment]
Hey @LukeStorry and @jsoref,
this is something that I would love to see as well. I added the Github action to my blog but since there's quite a lot of code blocks in there it gets quite painful to "allow" all those weird words in there.

Thanks for the great work. This is not really my domain, otherwise I'd offer to help.

**Comment by jsoref** [comment]
I'm still very much thinking about how I want to implement this feature since it's really the ability to parse arbitrary file content, and I also want to make sure I don't mess up line numbering (the current version doesn't worry about line numbering much, but 0.0.18-alpha which I hope to release shortly will be reporting each thing it finds w/ lines and columns, so not messing up line numbering will be even more important then).

One approach would be for me to just import someone else's parser. I haven't actively looked, but I'm fairly pessimistic about the odds that I'd find one I liked.

## Handling markdown snippets separately from other files today

@LukeStorry: fwiw, there is one approach that you could try today...
split the action into two jobs, one for markdown and one for code (you can use `only.txt` to focus on markdown for the one side). 

Note that what I'm writing below is entirely untested, there's a version in the [wiki which actually worked](https://github.com/check-spelling/check-spelling/wiki/Configuration%3A-Multiple-languages).

Use:
<details><summary>spelling workflow w/ matrix</summary>

`.github/workflows/spelling.yml` from https://github.com/check-spelling/spell-check-this/blob/prerelease/.github/workflows/spelling.yml
```yaml
name: Spell checking
on:
  pull_request_target:
  push:
  issue_comment:
  pull_request_review_comment:

jobs:
  spell-check:
    name: "Spell Checker"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        area: ["code", "markdown"]
    steps:
    - name: checkout-merge
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2.0.0
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
    - name: checkout
      if: "!contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2.0.0
    - uses: check-spelling/check-spelling@prerelease
      with:
        config: ".github/actions/spelling/${{ matrix.area }}"
        experimental_apply_changes_via_bot: 1
```
</details>

Follow the advice in the wiki for how to set up symlinks (note that `with: config: ...` will generate something similar to `env: bucket: ...` + `env: project: ...`).

<details><summary>Markdown patterns</summary>

In the `.github/actions/spelling/markdown/patterns/markdown.txt`:
```
^\s{4,}.*$
```
</details>

You'll want to actively use `common/allow.txt` (`allow.txt` wasn't available when the wiki page I'm linking to was written which is why it suggests `dictionary.txt`) to add words that are consistently used across your project -- symlinking it into `.github/actions/spelling/markdown/allow/common.txt` or similar.

## General thoughts on improving adoption

@pudgereyem: thanks for trying. I'm currently in the process of making the adoption easier.

looking at your blog repo, you could try using:

https://github.com/check-spelling/spell-check-this/blob/prerelease/.github/workflows/spelling.yml

### talk to the bot to update expect.txt

Specifically, if you make a PR to the default branch which has the above workflow, it'll let you automatically accept its suggestions for `expect.txt`.

### automatic updates for no newline at eof

Looking at your repository, I think I want it to automatically fix no-newline-at-eof -- the code already exists in the repository, so doing it would be pretty harmless. Unix tools (including git) really hate files that are missing the newline-at-eof, but Windows tools tend to make it really hard to understand how to fix this.

### automatic updates for excludes

I also want to set it up to be able to automatically update `excludes.txt` (the prerelease version offers suggestions for excludes). -- I'm not sure if I'll manage to get this into 0.0.18-alpha -- I kinda want to ship it (the feature to update expect has been in development since this past summer...).

### Building a list of corrections

The other thing that people would probably benefit from is my [little Google Sheet](https://docs.google.com/spreadsheets/d/1ehtjuiKF5mHUq_eVuz3lYB2Ui7XztEFBgnNjOmb9R20/edit?usp=sharing) that I use to calculate replacements... Google Sheets is really good at identifying real typos and suggesting real replacements.

-- Eventually, I intend to offer something like that via check-spelling: [Suggest corrections](https://github.com/check-spelling/check-spelling/wiki/Feature:-suggest-corrections), but that's really a long ways away (long after I handle multi-line blocks).
